import { StyleSheet } from 'react-native';
import type { ThemeColors } from '../../../theme/ThemeProvider';

export const makeStyles = (colors: ThemeColors) =>
  StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.background, paddingTop: 56 },
  loadingContainer: {
    flex: 1, justifyContent: 'center', alignItems: 'center', backgroundColor: colors.background,
  },
  header: {
    flexDirection: 'row', alignItems: 'center', paddingHorizontal: 20, marginBottom: 16, gap: 14,
  },
  headerCenter: { flex: 1, flexDirection: 'row', alignItems: 'center', gap: 12 },
  avatar: {
    width: 44, height: 44, borderRadius: 22, backgroundColor: colors.primaryDark,
    justifyContent: 'center', alignItems: 'center',
  },
  avatarText: {
    fontFamily: 'Inter_600SemiBold',
    color: colors.textOnPrimary,
    fontSize: 14,
    fontWeight: '600',
    letterSpacing: 1,
  },
  clientName: {
    fontFamily: 'CormorantGaramond_400Regular',
    fontSize: 24,
    lineHeight: 29,
    letterSpacing: 0.5,
    fontWeight: '400',
    color: colors.textPrimary,
  },
  clientStatus: {
    fontFamily: 'Inter_500Medium',
    fontSize: 11,
    lineHeight: 13,
    letterSpacing: 1.98,
    fontWeight: '500',
    textTransform: 'uppercase',
    color: colors.textMuted,
    marginTop: 4,
  },
  msgIconBtn: {
    width: 38, height: 38, borderRadius: 19, backgroundColor: colors.primaryPale,
    justifyContent: 'center', alignItems: 'center',
  },
  tabScroll: { maxHeight: 44, marginBottom: 16 },
  tabRow: { paddingHorizontal: 20, gap: 8 },
  tab: {
    flexDirection: 'row', alignItems: 'center', gap: 6,
    paddingVertical: 8, paddingHorizontal: 14, borderRadius: 4, // radius.lg
    backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border,
  },
  tabActive: { backgroundColor: colors.primary, borderColor: colors.primary },
  tabText: { fontFamily: 'Inter_500Medium', fontSize: 12, fontWeight: '500', color: colors.textSecondary, letterSpacing: 0.4 },
  tabTextActive: { color: colors.textOnPrimary },
  scrollContent: { paddingHorizontal: 20, paddingBottom: 100 },
  sectionTitle: {
    fontFamily: 'CormorantGaramond_500Medium',
    fontSize: 20,
    lineHeight: 24,
    letterSpacing: 0.4,
    fontWeight: '500',
    color: colors.textPrimary,
    marginBottom: 12,
    marginTop: 4,
  },
  // Calorie card
  calorieCard: {
    backgroundColor: colors.surface, borderRadius: 4, padding: 20, marginBottom: 16, alignItems: 'center',
  },
  calorieMain: { flexDirection: 'row', alignItems: 'baseline', gap: 4, marginBottom: 12 },
  calorieValue: {
    fontFamily: 'CormorantGaramond_400Regular',
    fontSize: 44,
    lineHeight: 46,
    letterSpacing: 0.4,
    fontWeight: '400',
    color: colors.textPrimary,
  },
  calorieTarget: { fontSize: 16, color: colors.textSecondary },
  caloriePctBg: { width: '100%', height: 6, borderRadius: 3, backgroundColor: colors.primaryPale },
  caloriePctFill: { height: '100%', borderRadius: 3, backgroundColor: colors.primary },
  caloriePctText: { fontSize: 12, color: colors.textMuted, marginTop: 6 },
  // Macro cards
  macroGrid: { flexDirection: 'row', gap: 10, marginBottom: 20 },
  macroCard: { flex: 1, backgroundColor: colors.surface, borderRadius: 2, padding: 14, alignItems: 'center', gap: 4 },
  macroCardValue: {
    fontFamily: 'CormorantGaramond_500Medium',
    fontSize: 22,
    lineHeight: 26,
    letterSpacing: 0.4,
    fontWeight: '500',
  },
  macroCardLabel: {
    fontFamily: 'Inter_500Medium',
    fontSize: 11,
    letterSpacing: 1.5,
    fontWeight: '500',
    textTransform: 'uppercase',
    color: colors.textMuted,
  },
  macroBarBg: { width: '100%', height: 4, borderRadius: 2, backgroundColor: colors.primaryPale, marginTop: 4 },
  macroBarFill: { height: '100%', borderRadius: 2 },
  macroCardTarget: { fontSize: 10, color: colors.textMuted },
  // Profile
  profileGrid: { backgroundColor: colors.surface, borderRadius: 2, padding: 16, gap: 12, marginBottom: 20 },
  profileRow: { flexDirection: 'row', justifyContent: 'space-between' },
  profileLabel: { fontFamily: 'Inter_400Regular', fontSize: 14, color: colors.textSecondary, textTransform: 'capitalize' },
  profileValue: { fontFamily: 'Inter_500Medium', fontSize: 14, fontWeight: '500', color: colors.textPrimary, textTransform: 'capitalize' },
  // Coach actions (messages + nudge)
  actionsRow: { flexDirection: 'row', gap: 10, marginBottom: 12 },
  actionPill: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 12,
    paddingHorizontal: 12,
    borderRadius: 4, // radius.lg
    backgroundColor: colors.primaryPale,
  },
  actionPillText: {
    fontFamily: 'Inter_500Medium',
    fontSize: 12,
    fontWeight: '500',
    letterSpacing: 1.2,
    textTransform: 'uppercase',
    color: colors.primary,
  },
  successBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingVertical: 10,
    paddingHorizontal: 14,
    backgroundColor: colors.success + '18',
    borderRadius: 4, // radius.lg
    marginBottom: 12,
  },
  successBannerText: { fontFamily: 'Inter_500Medium', fontSize: 13, fontWeight: '500', color: colors.success },
  nudgeModalOverlay: { flex: 1, backgroundColor: 'rgba(26,26,24,0.5)', justifyContent: 'center', alignItems: 'center' },
  nudgeModalContent: { width: '85%', backgroundColor: colors.surface, borderRadius: 4, padding: 24 },
  nudgeModalTitle: {
    fontFamily: 'CormorantGaramond_500Medium',
    fontSize: 22,
    lineHeight: 26,
    letterSpacing: 0.4,
    fontWeight: '500',
    color: colors.textPrimary,
    textAlign: 'center',
    marginBottom: 6,
  },
  nudgeModalDesc: { fontFamily: 'Inter_400Regular', fontSize: 13, color: colors.textSecondary, textAlign: 'center', marginBottom: 16, lineHeight: 18 },
  nudgeLabel: {
    fontFamily: 'Inter_500Medium',
    fontSize: 11,
    fontWeight: '500',
    letterSpacing: 1.98,
    color: colors.textMuted,
    textTransform: 'uppercase',
    marginBottom: 6,
    marginTop: 8,
  },
  nudgeInput: {
    backgroundColor: colors.surfaceElevated,
    borderRadius: 4, // radius.lg
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 15,
    color: colors.textPrimary,
  },
  nudgeInputMulti: { minHeight: 90, textAlignVertical: 'top' },
  nudgeErrorText: { color: colors.error, fontSize: 13, marginTop: 10, textAlign: 'center' },
  nudgeButtons: { flexDirection: 'row', gap: 12, marginTop: 20 },
  nudgeCancelBtn: { flex: 1, paddingVertical: 12, borderRadius: 4, backgroundColor: colors.surfaceElevated, alignItems: 'center' },
  nudgeCancelText: {
    fontFamily: 'Inter_500Medium',
    fontSize: 12,
    fontWeight: '500',
    letterSpacing: 1.2,
    textTransform: 'uppercase',
    color: colors.textSecondary,
  },
  nudgeSendBtn: { flex: 1, paddingVertical: 12, borderRadius: 4, backgroundColor: colors.primary, alignItems: 'center' },
  nudgeSendText: {
    fontFamily: 'Inter_500Medium',
    fontSize: 12,
    fontWeight: '500',
    letterSpacing: 1.2,
    textTransform: 'uppercase',
    color: colors.textOnPrimary,
  },
  // Logs
  logItem: { backgroundColor: colors.surface, borderRadius: 2, padding: 16, marginBottom: 10 },
  logHeader: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 6 },
  logMeal: {
    fontFamily: 'Inter_500Medium',
    fontSize: 11,
    fontWeight: '500',
    letterSpacing: 1.98,
    color: colors.textMuted,
    textTransform: 'uppercase',
  },
  logCalories: { fontFamily: 'Inter_500Medium', fontSize: 14, fontWeight: '500', color: colors.textPrimary },
  logFood: { fontFamily: 'Inter_500Medium', fontSize: 16, fontWeight: '500', color: colors.textPrimary, marginBottom: 4 },
  logMacros: { fontFamily: 'Inter_400Regular', fontSize: 13, color: colors.textSecondary },
  // Workouts
  sessionCard: { backgroundColor: colors.surface, borderRadius: 4, padding: 16, marginBottom: 10 },
  sessionTop: { flexDirection: 'row', alignItems: 'flex-start', marginBottom: 10 },
  sessionName: {
    fontFamily: 'CormorantGaramond_500Medium',
    fontSize: 20,
    lineHeight: 24,
    letterSpacing: 0.4,
    fontWeight: '500',
    color: colors.textPrimary,
  },
  sessionDate: { fontFamily: 'Inter_400Regular', fontSize: 12, color: colors.textSecondary, marginTop: 2 },
  completedBadge: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  completedText: { fontFamily: 'Inter_500Medium', fontSize: 12, fontWeight: '500', color: colors.success },
  inProgressText: { fontFamily: 'Inter_500Medium', fontSize: 12, fontWeight: '500', color: colors.warning },
  sessionStats: { flexDirection: 'row', gap: 8, marginBottom: 10 },
  sessionStat: {
    flex: 1, backgroundColor: colors.background, borderRadius: 4, padding: 10, alignItems: 'center',
  },
  sessionStatValue: {
    fontFamily: 'CormorantGaramond_500Medium',
    fontSize: 20,
    lineHeight: 24,
    letterSpacing: 0.4,
    fontWeight: '500',
    color: colors.textPrimary,
  },
  sessionStatLabel: {
    fontFamily: 'Inter_500Medium',
    fontSize: 10,
    fontWeight: '500',
    letterSpacing: 1.5,
    color: colors.textMuted,
    marginTop: 2,
    textTransform: 'uppercase',
  },
  sessionExercises: { fontFamily: 'Inter_400Regular', fontSize: 12, color: colors.textMuted },
  // Progress
  progressStatsRow: { flexDirection: 'row', gap: 10, marginBottom: 16 },
  progressStat: { flex: 1, backgroundColor: colors.surface, borderRadius: 2, padding: 14, alignItems: 'center', gap: 4 },
  progressStatValue: {
    fontFamily: 'CormorantGaramond_400Regular',
    fontSize: 28,
    lineHeight: 32,
    letterSpacing: 0.4,
    fontWeight: '400',
    color: colors.textPrimary,
  },
  progressStatLabel: {
    fontFamily: 'Inter_500Medium',
    fontSize: 11,
    fontWeight: '500',
    letterSpacing: 1.5,
    color: colors.textMuted,
    textTransform: 'uppercase',
  },
  // Meal plan
  planDayCard: { backgroundColor: colors.surface, borderRadius: 2, padding: 14, marginBottom: 10 },
  planDayLabel: { fontFamily: 'Inter_500Medium', fontSize: 14, fontWeight: '500', color: colors.textPrimary, marginBottom: 8 },
  planSlotRow: { flexDirection: 'row', alignItems: 'center', paddingVertical: 4 },
  planSlotLabel: { fontFamily: 'Inter_500Medium', fontSize: 12, fontWeight: '500', color: colors.textSecondary, width: 70 },
  planSlotMeal: { flex: 1, fontFamily: 'Inter_500Medium', fontSize: 13, fontWeight: '500', color: colors.textPrimary },
  planSlotCals: { fontFamily: 'Inter_500Medium', fontSize: 12, fontWeight: '500', color: colors.primary },
  planEmpty: { fontFamily: 'Inter_400Regular', fontSize: 13, color: colors.textMuted, fontStyle: 'italic' },
  // Empty
  emptyCard: { backgroundColor: colors.surface, borderRadius: 4, padding: 32, alignItems: 'center', gap: 8 },
  emptyText: { color: colors.textMuted, fontSize: 14, textAlign: 'center' },
  foodReviewHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 12,
    marginBottom: 8,
  },
  foodReviewChips: { flexDirection: 'row', gap: 6 },
  foodReviewChip: {
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 4,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
  },
  foodReviewChipActive: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  foodReviewChipText: { fontSize: 12, fontWeight: '600', color: colors.textSecondary },
  foodReviewChipTextActive: { color: colors.textOnPrimary },
  foodReviewDayCard: {
    backgroundColor: colors.surface,
    borderRadius: 4,
    padding: 12,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: colors.border,
  },
  foodReviewDayHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  foodReviewDayDate: { fontSize: 13, fontWeight: '600', color: colors.textPrimary },
  foodReviewDayTotal: { fontSize: 12, fontWeight: '600', color: colors.primary },
  // ── Server meal plans (coach side) ──
  mealPlansHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
    marginTop: 4,
  },
  createPlanBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: colors.primary,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 4, // radius.lg
  },
  createPlanBtnText: {
    fontFamily: 'Inter_500Medium',
    color: colors.textOnPrimary,
    fontSize: 12,
    fontWeight: '500',
    letterSpacing: 1.2,
    textTransform: 'uppercase',
  },
  retryBtn: {
    marginTop: 8,
    paddingHorizontal: 18,
    paddingVertical: 8,
    borderRadius: 4, // radius.lg
    backgroundColor: colors.primaryPale,
  },
  retryBtnText: {
    fontFamily: 'Inter_500Medium',
    fontSize: 12,
    fontWeight: '500',
    letterSpacing: 1.2,
    textTransform: 'uppercase',
    color: colors.primary,
  },
  serverPlanCard: {
    backgroundColor: colors.surface,
    borderRadius: 4, // radius.lg
    padding: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: colors.border,
  },
  serverPlanHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
    marginBottom: 8,
  },
  serverPlanTitle: {
    fontFamily: 'CormorantGaramond_500Medium',
    fontSize: 20,
    lineHeight: 24,
    letterSpacing: 0.4,
    fontWeight: '500',
    color: colors.textPrimary,
  },
  serverPlanMeta: { fontFamily: 'Inter_400Regular', fontSize: 12, color: colors.textMuted, marginTop: 4 },
  serverPlanActions: { flexDirection: 'row', gap: 4 },
  planIconBtn: {
    width: 34,
    height: 34,
    borderRadius: 4, // radius.lg
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: colors.primaryPale,
  },
  serverPlanNotes: {
    fontSize: 13,
    color: colors.textSecondary,
    lineHeight: 18,
    marginBottom: 8,
  },
  serverPlanEmpty: {
    fontSize: 13,
    color: colors.textMuted,
    fontStyle: 'italic',
    paddingVertical: 6,
  },
  serverPlanRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    paddingVertical: 8,
    borderTopWidth: 1,
    borderTopColor: colors.border,
    gap: 10,
  },
  serverPlanItemName: { fontFamily: 'Inter_500Medium', fontSize: 14, fontWeight: '500', color: colors.textPrimary },
  serverPlanItemTod: { fontFamily: 'Inter_400Regular', fontSize: 12, color: colors.textMuted },
  serverPlanItemNotes: { fontFamily: 'Inter_400Regular', fontSize: 12, color: colors.textMuted, marginTop: 2, lineHeight: 16 },
  serverPlanItemCal: { fontFamily: 'Inter_500Medium', fontSize: 12, fontWeight: '500', color: colors.textSecondary },
  serverPlanItemProt: { fontFamily: 'Inter_500Medium', fontSize: 11, fontWeight: '500', color: colors.primary, marginTop: 2 },
  // ── Plan form modal ──
  planModalContainer: { flex: 1, backgroundColor: colors.background },
  planModalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  planModalTitle: {
    fontFamily: 'CormorantGaramond_400Regular',
    fontSize: 24,
    lineHeight: 29,
    letterSpacing: 0.5,
    fontWeight: '400',
    color: colors.textPrimary,
  },
  planModalContent: { padding: 20, paddingBottom: 60 },
  planFieldLabel: {
    fontFamily: 'Inter_500Medium',
    fontSize: 11,
    fontWeight: '500',
    color: colors.textMuted,
    marginTop: 8,
    marginBottom: 6,
    textTransform: 'uppercase',
    letterSpacing: 1.98,
  },
  planInput: {
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 4, // radius.lg
    padding: 12,
    fontSize: 14,
    color: colors.textPrimary,
    marginBottom: 10,
  },
  planInputMulti: {
    minHeight: 70,
    textAlignVertical: 'top',
  },
  planItemsHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 8,
  },
  planAddItemBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 10,
    paddingVertical: 6,
    backgroundColor: colors.primaryPale,
    borderRadius: 4, // radius.lg
  },
  planAddItemText: {
    fontFamily: 'Inter_500Medium',
    fontSize: 11,
    fontWeight: '500',
    letterSpacing: 1.5,
    textTransform: 'uppercase',
    color: colors.primary,
  },
  planItemCard: {
    backgroundColor: colors.surface,
    borderRadius: 2, // radius.md
    padding: 12,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: colors.border,
  },
  planItemTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 6,
  },
  planItemIndex: { fontFamily: 'Inter_500Medium', fontSize: 12, fontWeight: '500', color: colors.textMuted },
  planItemInput: {
    backgroundColor: colors.background,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 0, // radius.sm
    padding: 10,
    fontSize: 13,
    color: colors.textPrimary,
    marginBottom: 8,
  },
  planItemRow: { flexDirection: 'row', gap: 8 },
  planFormError: {
    color: colors.error,
    fontSize: 13,
    marginTop: 4,
    marginBottom: 8,
  },
  planSubmitBtn: {
    backgroundColor: colors.primary,
    borderRadius: 2, // radius.md
    paddingVertical: 14,
    alignItems: 'center',
    marginTop: 12,
  },
  planSubmitText: {
    fontFamily: 'Inter_500Medium',
    fontSize: 13,
    fontWeight: '500',
    letterSpacing: 1.2,
    textTransform: 'uppercase',
    color: colors.textOnPrimary,
  },

  });

export type ClientDetailStyles = ReturnType<typeof makeStyles>;
