/**
 * Habits & check-in styles. The page (REDO-HABITS-CAL-COMM-133): date
 * overline, serif headline, underlined text tabs, one sentence for the day,
 * one forest action. Corners come from the radius tokens; no literal radius.
 */
import { StyleSheet } from 'react-native';
import type { ThemeColors } from '../../../theme/ThemeProvider';
import { layout, typography, type SemanticTokens } from '../../../theme/tokens';

export const makeStyles = (colors: ThemeColors, sc: SemanticTokens) =>
  StyleSheet.create({
  header: { marginTop: 8, marginBottom: 20, gap: 6 },
  tabRow: {
    flexDirection: 'row',
    gap: 24,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: sc.border,
    marginBottom: 8,
  },
  tab: { minHeight: layout.touchMin, justifyContent: 'center', borderBottomWidth: 2, borderBottomColor: 'transparent' },
  tabActive: { borderBottomColor: sc.accent },
  tabLabel: { ...typography.bodySmall, color: sc.textMuted },
  tabLabelActive: { ...typography.bodySmall, fontFamily: 'Inter_500Medium', fontWeight: '500', color: sc.textPrimary },
  pressed: { opacity: 0.6 },
  narrative: { ...typography.h2, color: sc.textPrimary, marginBottom: 6 },
  addLink: { marginTop: 12 },
  note: { ...typography.bodySmall, color: sc.textMuted },
  savedRow: { flexDirection: 'row', alignItems: 'center', gap: 8, minHeight: layout.touchMin },
  savedText: { ...typography.bodySmall, color: sc.accentText },
  habitCard: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderColor: sc.border,
    paddingVertical: 20,
  },
  habitLeft: { flexDirection: 'row', alignItems: 'center', flex: 1, gap: 12 },
  habitIconBox: {
    width: 44,
    height: 44,
    borderRadius: 2, // radius.md
    justifyContent: 'center',
    alignItems: 'center',
  },
  habitInfo: { flex: 1, gap: 4 },
  habitName: { fontFamily: 'Inter_500Medium', fontSize: 15, fontWeight: '500', color: colors.textPrimary },
  habitNameDone: { textDecorationLine: 'line-through', color: colors.textMuted },
  habitMeta: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  runText: { fontFamily: 'Inter_400Regular', fontSize: 13, color: colors.textMuted },
  habitTarget: { fontFamily: 'Inter_400Regular', fontSize: 13, fontVariant: ['tabular-nums'], color: colors.textMuted },
  weekDots: { flexDirection: 'row', gap: 6, marginTop: 4 },
  weekDotCol: { alignItems: 'center', gap: 2 },
  weekDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: colors.border,
  },
  weekDotLabel: { fontFamily: 'Inter_400Regular', fontSize: 13, color: colors.textMuted },
  checkCircle: {
    width: 44,
    height: 44,
    borderRadius: 4, // radius.lg
    borderWidth: 1,
    borderColor: colors.border,
    justifyContent: 'center',
    alignItems: 'center',
  },
  checkInCard: {
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderColor: sc.border,
    paddingVertical: 20,
    marginBottom: 12,
  },
  checkInLabel: {
    fontFamily: 'Inter_500Medium',
    fontSize: 15,
    lineHeight: 22,
    letterSpacing: 0.4,
    fontWeight: '500',
    color: colors.textPrimary,
    marginBottom: 12,
  },
  ratingRow: { flexDirection: 'row', justifyContent: 'space-between' },
  ratingBtn: {
    alignItems: 'center',
    paddingVertical: 8,
    minHeight: 44,
    minWidth: 44,
    paddingHorizontal: 0,
    borderRadius: 2, // radius.md
    flex: 1,
  },
  ratingBtnActive: {
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderColor: colors.primary,
  },
  ratingEmoji: { fontSize: 22 },
  ratingLabel: {
    fontFamily: 'Inter_500Medium',
    fontSize: 13,
    lineHeight: 18,
    textAlign: 'center',
    fontWeight: '500',
    letterSpacing: 0,
    color: colors.textMuted,
    marginTop: 4,
  },
  ratingLabelActive: { color: colors.primary, fontWeight: '500' },
  sleepRow: { flexDirection: 'row', gap: 20 },
  sleepControl: { flex: 1 },
  sleepLabel: {
    fontFamily: 'Inter_500Medium',
    fontSize: 13,
    fontWeight: '500',
    letterSpacing: 0,
    color: colors.textMuted,
    marginBottom: 8,
  },
  stepperRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 12 },
  stepperBtn: {
    width: 44,
    height: 44,
    borderRadius: 4, // radius.lg
    backgroundColor: sc.bgPrimary,
    borderWidth: 1,
    borderColor: colors.border,
    justifyContent: 'center',
    alignItems: 'center',
  },
  stepperValue: {
    fontFamily: 'Inter_500Medium',
    fontSize: 20,
    fontVariant: ['tabular-nums'],
    lineHeight: 26,
    letterSpacing: 0.4,
    fontWeight: '500',
    color: colors.textPrimary,
    minWidth: 50,
    textAlign: 'center',
  },
  qualityRow: { flexDirection: 'row', justifyContent: 'center', gap: 6 },
  stressDot: { width: 16, height: 16, borderRadius: 0, marginBottom: 4 },
  notesInput: {
    backgroundColor: sc.bgPrimary,
    fontFamily: 'Inter_400Regular',
    borderRadius: 2, // radius.md
    padding: 14,
    fontSize: 14,
    color: colors.textPrimary,
    minHeight: 80,
    textAlignVertical: 'top',
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderColor: colors.border,
  },
  saveBtn: { marginTop: 8 },
  modalOverlay: {
    flex: 1,
    backgroundColor: sc.overlay,
    justifyContent: 'flex-end',
  },
  modalContent: {
    backgroundColor: sc.bgPrimary,
    borderTopLeftRadius: 4,
    borderTopRightRadius: 4,
    padding: 24,
    paddingBottom: 40,
    maxHeight: '85%',
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  modalTitle: {
    fontFamily: 'CormorantGaramond_400Regular',
    fontSize: 24,
    lineHeight: 29,
    letterSpacing: 0.5,
    fontWeight: '400',
    color: colors.textPrimary,
  },
  fieldLabel: {
    fontFamily: 'Inter_500Medium',
    fontSize: 13,
    fontWeight: '500',
    letterSpacing: 0,
    color: colors.textMuted,
    marginBottom: 8,
    marginTop: 12,
  },
  fieldInput: {
    backgroundColor: sc.bgPrimary,
    fontFamily: 'Inter_400Regular',
    borderRadius: 2, // radius.md
    padding: 14,
    fontSize: 15,
    color: colors.textPrimary,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderColor: colors.border,
  },
  iconGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  iconOption: {
    width: 40,
    height: 40,
    borderRadius: 4, // radius.lg
    backgroundColor: colors.surface,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: colors.border,
  },
  iconOptionActive: { borderColor: colors.primary, backgroundColor: colors.primaryPale },
  colorGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  colorOption: {
    width: 32,
    height: 32,
    borderRadius: 4, // radius.lg
  },
  colorOptionActive: { borderWidth: 3, borderColor: colors.textPrimary },
  targetRow: { flexDirection: 'row', gap: 12 },
  targetField: { flex: 1 },
  modalSaveBtn: {
    backgroundColor: sc.accent,
    borderRadius: 4, // radius.lg
    paddingVertical: 16,
    alignItems: 'center',
    marginTop: 20,
  },
  modalSaveBtnDisabled: { backgroundColor: sc.disabledBg },
  modalSaveBtnText: {
    fontFamily: 'Inter_500Medium',
    fontSize: 13,
    fontWeight: '500',
    letterSpacing: 0,
    color: sc.textOnAccent,
  },

  });

export type HabitsStyles = ReturnType<typeof makeStyles>;
