/**
 * Habits & check-in styles (REDO-HABITS-CAL-COMM-133). Bone page, hairline
 * rows, serif names and numbers, one forest action. Corners come from the
 * radius tokens (owner 17:07, decision 133-4); no literal radius here.
 */
import { StyleSheet } from 'react-native';
import { layout, radius, typography, type SemanticTokens } from '../../../theme/tokens';

export const makeStyles = (sc: SemanticTokens) =>
  StyleSheet.create({
  header: { marginTop: 8, marginBottom: 20, gap: 6 },
  tabRow: {
    flexDirection: 'row',
    gap: 24,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: sc.border,
    marginBottom: 8,
  },
  tab: { minHeight: layout.touchMin, justifyContent: 'center', borderBottomWidth: 2, borderBottomColor: 'transparent' },
  tabActive: { borderBottomColor: sc.accent },
  tabLabel: { ...typography.bodySmall, color: sc.textMuted },
  tabLabelActive: { ...typography.bodySmall, fontFamily: 'Inter_500Medium', fontWeight: '500', color: sc.textPrimary },
  pressed: { opacity: 0.6 },
  narrative: { ...typography.h2, color: sc.textPrimary, marginBottom: 6 },
  // ── Habit rows ──
  habitRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 16,
    minHeight: layout.rowMinHeight,
    paddingVertical: 18,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: sc.border,
  },
  checkCircle: {
    width: 28,
    height: 28,
    marginTop: 2,
    borderRadius: radius.chip,
    borderWidth: 1,
    borderColor: sc.textMuted,
    alignItems: 'center',
    justifyContent: 'center',
  },
  checkCircleDone: { borderColor: sc.accent },
  habitInfo: { flex: 1, gap: 4 },
  habitName: { ...typography.h3, color: sc.textPrimary },
  habitNameDone: { color: sc.textMuted, textDecorationLine: 'line-through' },
  habitTarget: { ...typography.bodySmall, color: sc.textMuted, fontVariant: ['tabular-nums'] },
  weekDots: { flexDirection: 'row', gap: 14, marginTop: 10 },
  weekDotCol: { alignItems: 'center', gap: 6 },
  weekDotLabel: { ...typography.caption, letterSpacing: 0.6, color: sc.textMuted },
  weekDotLabelToday: { color: sc.textPrimary },
  weekDot: { width: 8, height: 8, borderRadius: radius.chip, borderWidth: 1, borderColor: sc.border },
  weekDotDone: { backgroundColor: sc.accent, borderColor: sc.accent },
  weekDotToday: { borderColor: sc.accent },
  addLink: { marginTop: 12 },
  // ── Check-in ──
  note: { ...typography.bodySmall, color: sc.textMuted },
  savedRow: { flexDirection: 'row', alignItems: 'center', gap: 8, minHeight: layout.touchMin },
  savedText: { ...typography.bodySmall, color: sc.accentText },
  prompt: { ...typography.h3, color: sc.textPrimary, marginBottom: 14 },
  ratingRow: { flexDirection: 'row', justifyContent: 'space-between' },
  ratingBtn: { flex: 1, minHeight: layout.touchMin, minWidth: layout.touchMin, alignItems: 'center', gap: 8, paddingVertical: 6 },
  ratingDot: { width: 14, height: 14, borderRadius: radius.chip, borderWidth: 1, borderColor: sc.textMuted },
  ratingDotActive: { backgroundColor: sc.accent, borderColor: sc.accent },
  ratingLabel: { ...typography.caption, letterSpacing: 0, color: sc.textMuted, textAlign: 'center' },
  ratingLabelActive: { color: sc.textPrimary },
  stepperRow: { flexDirection: 'row', alignItems: 'center', gap: 20 },
  stepperBtn: {
    width: layout.touchMin,
    height: layout.touchMin,
    borderRadius: radius.chip,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: sc.textMuted,
    alignItems: 'center',
    justifyContent: 'center',
  },
  stepperValue: {
    ...typography.h1,
    color: sc.textPrimary,
    fontVariant: ['tabular-nums'],
    minWidth: 72,
    textAlign: 'center',
  },
  notesInput: {
    ...typography.body,
    color: sc.textPrimary,
    backgroundColor: sc.bgSurface,
    borderRadius: radius.input,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: sc.border,
    paddingHorizontal: 16,
    paddingTop: 14,
    paddingBottom: 14,
    minHeight: 104,
    textAlignVertical: 'top',
  },
  saveBtn: { marginTop: 8 },
  // ── Add habit sheet ──
  modalOverlay: { flex: 1, backgroundColor: sc.overlay, justifyContent: 'flex-end' },
  sheet: {
    backgroundColor: sc.bgPrimary,
    borderTopLeftRadius: radius.sheet,
    borderTopRightRadius: radius.sheet,
    paddingHorizontal: layout.gutter,
    paddingTop: 10,
    maxHeight: '85%',
  },
  grabber: { alignSelf: 'center', width: 36, height: 4, borderRadius: radius.chip, backgroundColor: sc.border, marginBottom: 14 },
  sheetHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  closeBtn: { width: layout.touchMin, height: layout.touchMin, borderRadius: radius.chip, alignItems: 'center', justifyContent: 'center', marginRight: -10 },
  fieldLabel: { ...typography.eyebrow, color: sc.textMuted, marginTop: 20, marginBottom: 8 },
  fieldInput: {
    ...typography.body,
    color: sc.textPrimary,
    backgroundColor: sc.bgSurface,
    borderRadius: radius.input,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: sc.border,
    paddingHorizontal: 16,
    minHeight: 52,
  },
  targetRow: { flexDirection: 'row', gap: 12 },
  targetField: { flex: 1 },
  sheetSave: { marginTop: 28 },
  });

export type HabitsStyles = ReturnType<typeof makeStyles>;
