import { StyleSheet } from 'react-native';
import type { ThemeColors } from '../../../theme/ThemeProvider';
import type { SemanticTokens } from '../../../theme/tokens';

export const makeStyles = (colors: ThemeColors, sc: SemanticTokens) =>
  StyleSheet.create({
  container: { flex: 1, backgroundColor: sc.bgPrimary },
  header: { paddingHorizontal: 24, paddingTop: 60, marginBottom: 24 },
  title: {
    fontFamily: 'CormorantGaramond_400Regular',
    fontSize: 32,
    lineHeight: 35,
    letterSpacing: 0.6,
    fontWeight: '400',
    color: colors.textPrimary,
  },
  subtitle: {
    fontFamily: 'Inter_500Medium',
    fontSize: 11,
    lineHeight: 13,
    letterSpacing: 1.98,
    fontWeight: '500',
    textTransform: 'uppercase',
    color: colors.textMuted,
    marginTop: 8,
  },
  tabRow: {
    flexDirection: 'row',
    paddingHorizontal: 24,
    gap: 10,
    marginBottom: 12,
  },
  tabBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 16,
    minHeight: 44,
    paddingVertical: 12,
    borderRadius: 4, // radius.lg
    backgroundColor: sc.bgPrimary,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderColor: colors.border,
  },
  tabBtnActive: {
    backgroundColor: sc.bgPrimary,
    borderColor: colors.primary,
  },
  tabLabel: {
    fontFamily: 'Inter_500Medium',
    fontSize: 13,
    fontWeight: '500',
    letterSpacing: 0.4,
    color: colors.textSecondary,
  },
  tabLabelActive: { color: colors.primary },
  dotBadge: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: colors.error,
  },
  scrollContent: { paddingHorizontal: 24 },
  progressCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: sc.bgPrimary,
    borderRadius: 4, // radius.lg
    paddingVertical: 24,
    marginBottom: 8,
    gap: 20,
  },
  progressCircle: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: colors.primaryPale,
    justifyContent: 'center',
    alignItems: 'center',
  },
  progressPct: {
    fontFamily: 'CormorantGaramond_500Medium',
    fontSize: 22,
    lineHeight: 26,
    letterSpacing: 0.4,
    fontWeight: '500',
    color: colors.primary,
  },
  progressLabel: {
    fontFamily: 'Inter_500Medium',
    fontSize: 10,
    fontWeight: '500',
    letterSpacing: 1.5,
    textTransform: 'uppercase',
    color: colors.textMuted,
  },
  progressStats: { flex: 1, gap: 6 },
  progressStatValue: {
    fontFamily: 'CormorantGaramond_500Medium',
    fontSize: 28,
    lineHeight: 34,
    fontVariant: ['tabular-nums'],
    letterSpacing: 0.4,
    fontWeight: '500',
    color: colors.textPrimary,
  },
  progressStatLabel: { fontFamily: 'Inter_400Regular', fontSize: 13, color: colors.textSecondary },
  progressBar: {
    height: 6,
    borderRadius: 3,
    backgroundColor: colors.border,
    overflow: 'hidden',
  },
  progressBarFill: {
    height: 6,
    borderRadius: 3,
    backgroundColor: colors.primary,
  },
  habitCard: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderColor: sc.border,
    paddingVertical: 20,
  },
  habitLeft: { flexDirection: 'row', alignItems: 'center', flex: 1, gap: 12 },
  habitIconBox: {
    width: 44,
    height: 44,
    borderRadius: 2, // radius.md
    justifyContent: 'center',
    alignItems: 'center',
  },
  habitInfo: { flex: 1, gap: 4 },
  habitName: { fontFamily: 'Inter_500Medium', fontSize: 15, fontWeight: '500', color: colors.textPrimary },
  habitNameDone: { textDecorationLine: 'line-through', color: colors.textMuted },
  habitMeta: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  runText: { fontFamily: 'Inter_400Regular', fontSize: 13, color: colors.textMuted },
  habitTarget: { fontFamily: 'Inter_400Regular', fontSize: 13, fontVariant: ['tabular-nums'], color: colors.textMuted },
  weekDots: { flexDirection: 'row', gap: 6, marginTop: 4 },
  weekDotCol: { alignItems: 'center', gap: 2 },
  weekDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: colors.border,
  },
  weekDotLabel: { fontFamily: 'Inter_400Regular', fontSize: 13, color: colors.textMuted },
  checkCircle: {
    width: 44,
    height: 44,
    borderRadius: 4, // radius.lg
    borderWidth: 1,
    borderColor: colors.border,
    justifyContent: 'center',
    alignItems: 'center',
  },
  addBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 14,
    borderRadius: 4, // radius.lg
    minHeight: 44,
    marginTop: 4,
  },
  addBtnText: {
    fontFamily: 'Inter_500Medium',
    fontSize: 13,
    fontWeight: '500',
    letterSpacing: 0,
    color: colors.primary,
  },
  savedBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: sc.bgPrimary,
    padding: 12,
    borderRadius: 2, // radius.md
    marginBottom: 16,
  },
  savedBannerText: { fontFamily: 'Inter_500Medium', fontSize: 13, fontWeight: '500', color: colors.primary },
  lastCheckInRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 12,
    paddingHorizontal: 4,
  },
  lastCheckInText: { fontFamily: 'Inter_400Regular', fontSize: 13, color: colors.textMuted },
  checkInCard: {
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderColor: sc.border,
    paddingVertical: 20,
    marginBottom: 12,
  },
  checkInLabel: {
    fontFamily: 'Inter_500Medium',
    fontSize: 15,
    lineHeight: 22,
    letterSpacing: 0.4,
    fontWeight: '500',
    color: colors.textPrimary,
    marginBottom: 12,
  },
  ratingRow: { flexDirection: 'row', justifyContent: 'space-between' },
  ratingBtn: {
    alignItems: 'center',
    paddingVertical: 8,
    minHeight: 44,
    minWidth: 44,
    paddingHorizontal: 0,
    borderRadius: 2, // radius.md
    flex: 1,
  },
  ratingBtnActive: {
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderColor: colors.primary,
  },
  ratingEmoji: { fontSize: 22 },
  ratingLabel: {
    fontFamily: 'Inter_500Medium',
    fontSize: 13,
    lineHeight: 18,
    textAlign: 'center',
    fontWeight: '500',
    letterSpacing: 0,
    color: colors.textMuted,
    marginTop: 4,
  },
  ratingLabelActive: { color: colors.primary, fontWeight: '500' },
  sleepRow: { flexDirection: 'row', gap: 20 },
  sleepControl: { flex: 1 },
  sleepLabel: {
    fontFamily: 'Inter_500Medium',
    fontSize: 13,
    fontWeight: '500',
    letterSpacing: 0,
    color: colors.textMuted,
    marginBottom: 8,
  },
  stepperRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 12 },
  stepperBtn: {
    width: 44,
    height: 44,
    borderRadius: 4, // radius.lg
    backgroundColor: sc.bgPrimary,
    borderWidth: 1,
    borderColor: colors.border,
    justifyContent: 'center',
    alignItems: 'center',
  },
  stepperValue: {
    fontFamily: 'Inter_500Medium',
    fontSize: 20,
    fontVariant: ['tabular-nums'],
    lineHeight: 26,
    letterSpacing: 0.4,
    fontWeight: '500',
    color: colors.textPrimary,
    minWidth: 50,
    textAlign: 'center',
  },
  qualityRow: { flexDirection: 'row', justifyContent: 'center', gap: 6 },
  stressDot: { width: 16, height: 16, borderRadius: 0, marginBottom: 4 },
  notesInput: {
    backgroundColor: sc.bgPrimary,
    fontFamily: 'Inter_400Regular',
    borderRadius: 2, // radius.md
    padding: 14,
    fontSize: 14,
    color: colors.textPrimary,
    minHeight: 80,
    textAlignVertical: 'top',
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderColor: colors.border,
  },
  saveBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: sc.accent,
    borderRadius: 4, // radius.lg
    paddingVertical: 16,
    marginTop: 8,
  },
  saveBtnText: {
    fontFamily: 'Inter_500Medium',
    fontSize: 13,
    fontWeight: '500',
    letterSpacing: 0,
    color: sc.textOnAccent,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: sc.overlay,
    justifyContent: 'flex-end',
  },
  modalContent: {
    backgroundColor: sc.bgPrimary,
    borderTopLeftRadius: 4,
    borderTopRightRadius: 4,
    padding: 24,
    paddingBottom: 40,
    maxHeight: '85%',
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  modalTitle: {
    fontFamily: 'CormorantGaramond_400Regular',
    fontSize: 24,
    lineHeight: 29,
    letterSpacing: 0.5,
    fontWeight: '400',
    color: colors.textPrimary,
  },
  fieldLabel: {
    fontFamily: 'Inter_500Medium',
    fontSize: 13,
    fontWeight: '500',
    letterSpacing: 0,
    color: colors.textMuted,
    marginBottom: 8,
    marginTop: 12,
  },
  fieldInput: {
    backgroundColor: sc.bgPrimary,
    fontFamily: 'Inter_400Regular',
    borderRadius: 2, // radius.md
    padding: 14,
    fontSize: 15,
    color: colors.textPrimary,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderColor: colors.border,
  },
  iconGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  iconOption: {
    width: 40,
    height: 40,
    borderRadius: 4, // radius.lg
    backgroundColor: colors.surface,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: colors.border,
  },
  iconOptionActive: { borderColor: colors.primary, backgroundColor: colors.primaryPale },
  colorGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  colorOption: {
    width: 32,
    height: 32,
    borderRadius: 4, // radius.lg
  },
  colorOptionActive: { borderWidth: 3, borderColor: colors.textPrimary },
  targetRow: { flexDirection: 'row', gap: 12 },
  targetField: { flex: 1 },
  modalSaveBtn: {
    backgroundColor: sc.accent,
    borderRadius: 4, // radius.lg
    paddingVertical: 16,
    alignItems: 'center',
    marginTop: 20,
  },
  modalSaveBtnDisabled: { backgroundColor: sc.disabledBg },
  modalSaveBtnText: {
    fontFamily: 'Inter_500Medium',
    fontSize: 13,
    fontWeight: '500',
    letterSpacing: 0,
    color: sc.textOnAccent,
  },

  });

export type HabitsStyles = ReturnType<typeof makeStyles>;
