import { StyleSheet } from 'react-native';
import type { ThemeColors } from '../../../theme/ThemeProvider';
import { layout, lightTokens as sc, radius } from '../../../theme/tokens';

// REDO-LIVE-133 (owner 17:07, decision 133-4): every corner comes from the
// semantic radius tokens; the page margin is layout.gutter (24). The live
// workout takes its insets, top bar and Finish button from src/ui (Screen,
// ScreenTopBar, PrimaryButton). topBar / topCenter / topTitle / finishBtn /
// content are kept for WorkoutHistoryEditScreen, which shares these styles.

export const makeStyles = (colors: ThemeColors) =>
  StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.background },
  topBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: layout.gutter,
    paddingTop: 56,
    paddingBottom: 12,
    backgroundColor: colors.background,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: sc.border,
  },
  topCenter: { alignItems: 'center', flex: 1, paddingHorizontal: 8 },
  topTitle: { fontFamily: 'Inter_500Medium', fontSize: 16, fontWeight: '500', color: colors.textPrimary },
  timerText: { fontFamily: 'Inter_500Medium', fontVariant: ['tabular-nums'], fontSize: 17, lineHeight: 22, fontWeight: '500', color: colors.textPrimary, letterSpacing: 0.3 },
  finishBtn: {
    backgroundColor: colors.primary,
    borderRadius: radius.button,
    paddingHorizontal: 16,
    paddingVertical: 8,
  },
  finishBtnText: { fontFamily: 'Inter_500Medium', color: colors.textOnPrimary, fontSize: 14, fontWeight: '500' },
  // Live workout hero: overline, serif name (Headline), set count, hairline progress.
  screenContent: { paddingHorizontal: 0, paddingTop: 8 },
  hero: {
    marginHorizontal: layout.gutter,
    paddingBottom: 24,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: sc.border,
  },
  heroMeta: { fontFamily: 'Inter_400Regular', fontVariant: ['tabular-nums'], fontSize: 14, lineHeight: 20, color: sc.textMuted, marginTop: 8 },
  progressBar: {
    height: 2,
    marginTop: 16,
    borderRadius: radius.chip,
    backgroundColor: sc.border,
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    borderRadius: radius.chip,
    backgroundColor: colors.primary,
  },
  listOverline: { marginHorizontal: layout.gutter, marginTop: 28, marginBottom: 0 },
  emptyList: { fontFamily: 'Inter_400Regular', fontSize: 14, lineHeight: 20, color: sc.textMuted, marginHorizontal: layout.gutter, marginTop: 8 },
  readback: { marginHorizontal: layout.gutter - 16, marginTop: 12 },
  content: { paddingVertical: 16, paddingBottom: 100 },
  exerciseCard: {
    marginHorizontal: layout.gutter,
    backgroundColor: colors.background,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: sc.border,
    paddingVertical: 20,
  },
  exerciseHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
    marginBottom: 8,
  },
  exerciseHeaderText: { flex: 1, gap: 2 },
  exerciseName: { fontFamily: 'Inter_500Medium', fontSize: 17, lineHeight: 24, fontWeight: '500', color: colors.textPrimary },
  exerciseSummary: { fontFamily: 'Inter_400Regular', fontVariant: ['tabular-nums'], fontSize: 13, lineHeight: 18, color: sc.textMuted },
  coachNote: { fontFamily: 'Inter_400Regular', fontSize: 14, lineHeight: 20, color: colors.textSecondary, marginTop: 4, marginBottom: 4 },
  exerciseTools: { flexDirection: 'row', alignItems: 'center', gap: 4, marginVertical: 4 },
  exerciseRestTools: { flexDirection: 'row', alignItems: 'center', gap: 4, marginBottom: 8 },
  toolButton: { minHeight: 44, minWidth: 44, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 4 },
  toolButtonDisabled: { opacity: 0.4 },
  previousSet: { width: 68, minHeight: 44, justifyContent: 'center', alignItems: 'center' },
  previousSetLabel: { fontFamily: 'Inter_400Regular', fontSize: 13, color: sc.textMuted },
  previousSetValue: { fontFamily: 'Inter_500Medium', fontVariant: ['tabular-nums'], fontSize: 13, color: colors.textSecondary },
  previousSetText: { fontFamily: 'Inter_400Regular', fontSize: 13, color: colors.textSecondary },
  notesInput: {
    fontFamily: 'Inter_400Regular',
    minHeight: 48,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 14,
    lineHeight: 20,
    color: colors.textPrimary,
    backgroundColor: colors.background,
    borderRadius: radius.input,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: sc.border,
    textAlignVertical: 'top',
    marginTop: 8,
  },
  notesSection: { marginHorizontal: layout.gutter, paddingTop: 24, paddingBottom: 8 },
  setHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 6,
    gap: 4,
    paddingRight: 72, // Reserve the trailing Previous cell without changing ExerciseCard.
  },
  setHeaderText: { fontFamily: 'Inter_500Medium', fontSize: 13, fontWeight: '500', letterSpacing: 0.3, color: sc.textMuted, textAlign: 'center' },
  setRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    marginBottom: 4,
    paddingVertical: 4,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: sc.border,
  },
  // A done set reads as a soft forest tint with rounded ends, no hairline under it.
  setRowCompleted: { backgroundColor: colors.primaryPale, borderRadius: radius.input, borderBottomColor: colors.primaryPale },
  setText: { fontFamily: 'Inter_600SemiBold', fontVariant: ['tabular-nums'], fontSize: 14, fontWeight: '600', color: colors.textSecondary, textAlign: 'center' },
  setInput: {
    backgroundColor: colors.background,
    borderRadius: radius.input,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: sc.border,
    paddingVertical: 12,
    paddingHorizontal: 4,
    minWidth: 44,
    minHeight: 44,
    fontFamily: 'Inter_600SemiBold',
    fontVariant: ['tabular-nums'],
    fontSize: 15,
    fontWeight: '600',
    color: colors.textPrimary,
    textAlign: 'center',
  },
  // The completion mark is a circle, as in the clientfile-workouts reference.
  checkBtn: {
    width: 44,
    height: 44,
    borderRadius: radius.chip,
    backgroundColor: colors.background,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: sc.border,
  },
  checkBtnDone: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  addSetBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    gap: 6,
    minHeight: 44,
    paddingRight: 8,
    marginTop: 4,
  },
  addSetText: { fontFamily: 'Inter_500Medium', fontSize: 14, fontWeight: '500', color: colors.primary },
  // A quiet hairline row, not a dashed box: the page keeps one filled action (Finish).
  addExerciseBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginHorizontal: layout.gutter,
    minHeight: layout.rowMinHeight,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: sc.border,
  },
  addExerciseText: { fontFamily: 'Inter_500Medium', fontSize: 15, fontWeight: '500', color: colors.primary },

  // Modal
  modalContainer: { flex: 1, backgroundColor: colors.background },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: layout.gutter,
    paddingTop: 16,
    paddingBottom: 12,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: sc.border,
  },
  modalClose: { width: layout.touchMin, height: layout.touchMin, justifyContent: 'center' },
  modalTitle: { fontFamily: 'Inter_500Medium', fontSize: 17, fontWeight: '500', color: colors.textPrimary },
  searchBar: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.background,
    marginHorizontal: layout.gutter,
    marginTop: 16,
    marginBottom: 12,
    borderRadius: radius.input,
    paddingHorizontal: 14,
    minHeight: 48,
    gap: 8,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: sc.border,
  },
  searchInput: { fontFamily: 'Inter_400Regular', flex: 1, fontSize: 16, color: colors.textPrimary },
  muscleFilter: { maxHeight: 44, marginBottom: 8 },
  muscleFilterContent: { paddingHorizontal: layout.gutter, gap: 8, alignItems: 'center' },
  // Pill chips; the chosen one is outlined in forest, never filled (one filled action per screen).
  muscleChip: {
    minHeight: 36,
    justifyContent: 'center',
    paddingHorizontal: 16,
    borderRadius: radius.chip,
    backgroundColor: colors.background,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: sc.border,
  },
  muscleChipActive: { borderColor: colors.primary, borderWidth: 1 },
  muscleChipText: { fontFamily: 'Inter_500Medium', fontSize: 13, fontWeight: '500', color: colors.textSecondary },
  muscleChipTextActive: { color: colors.primary },
  exerciseList: { paddingHorizontal: layout.gutter, paddingBottom: 40 },

  // Exercise list item with image
  exerciseListItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingVertical: 12,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: sc.border,
  },
  exerciseListInfo: {
    flex: 1,
    gap: 4,
  },
  exerciseListName: { fontFamily: 'Inter_500Medium', fontSize: 15, fontWeight: '500', color: colors.textPrimary },
  exerciseListEquipment: { fontFamily: 'Inter_400Regular', fontSize: 13, color: sc.textMuted },

  // Empty state
  emptyState: {
    alignItems: 'center',
    paddingTop: 48,
    paddingBottom: 24,
    gap: 8,
  },
  emptyStateText: {
    fontFamily: 'Inter_500Medium',
    fontSize: 16,
    fontWeight: '500',
    color: colors.textPrimary,
    marginTop: 8,
  },
  emptyStateSubtext: {
    fontFamily: 'Inter_400Regular',
    fontSize: 13,
    color: sc.textMuted,
    textAlign: 'center',
    paddingHorizontal: 32,
  },

  // Rest timer: a hairline row in the pinned footer, above Finish (no shadow, no float).
  restOverlay: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    minHeight: layout.rowMinHeight,
    paddingLeft: 16,
    paddingRight: 4,
    borderRadius: radius.card,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: sc.border,
    backgroundColor: colors.background,
  },
  restLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    flex: 1,
  },
  restLabel: {
    fontFamily: 'Inter_500Medium',
    fontSize: 13,
    color: colors.textSecondary,
    fontWeight: '500',
  },
  restCountdown: {
    fontFamily: 'Inter_500Medium',
    fontVariant: ['tabular-nums'],
    fontSize: 22,
    lineHeight: 28,
    fontWeight: '500',
    color: colors.textPrimary,
    marginRight: 4,
  },
  restSkip: {
    fontFamily: 'Inter_500Medium',
    fontSize: 14,
    color: colors.primary,
    fontWeight: '500',
  },

  });

export type ActiveWorkoutStyles = ReturnType<typeof makeStyles>;
